### ISSUE TITLE
Extract sanitization to separate class

### ISSUE THREAD

**Issue by miquelp** [miquelp/CsvImporter#7]
Now `CsvImporterMysqlBuilder` implements sanitization methods (so far ` sanitizeColumn` and ` sanitizeColumn`) which violates Single Responsibility Principle of SOLID principle.

These sanitization methods should be extracted to a separate "sanitization" class and then injected to CsvImporterMysqlBuilder via constructor.

**Comment by mql21** [comment]
Done
